server:
  port: "12345"  # TCP监听端口
  http_port: "8888"  # HTTP服务器端口

audio:
  sample_rate: 48000    # 采样率
  channels: 2           # 声道数
  buffer_size:  1025   # 缓冲区大小 乘以声道数 为0时自动计算 最大4096
  device_name: ""       # 指定设备名称
  auto_select: false    # 选择系统默认输入设备
  prefer_blackhole: true

processing:  #节流选项 服务端静音状态时休眠节流
  silence_detection: false #是否开启静音检测
  silence_threshold: 1000 #静音阈值
  clip_threshold: 28000 #削波阈值 （-32768 - 32767）

  volume_multiplier: 1.0 #音量增益 原始1.0

protocols:
  tcp:
    enabled: true  # TCP协议（推荐）
  http:
    enabled: true # HTTP协议